apiVersion: v1
kind: Service
metadata:
  name: cafe-test-backend
  namespace: cafe-test
spec:
  selector:
    app: cafe-test-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
