"""Generate V2__seed.sql from MENU_AROGYA_Organized.xlsx.

Deterministic (uuid5) so the migration is stable and re-runnable. Quantities on hand and
reorder thresholds default to 0 — the owner sets real levels and suppliers after seeding.
Run: python scripts/gen_seed.py
"""

import uuid
import openpyxl

NS = uuid.UUID("00000000-0000-0000-0000-0000a0000a00")  # fixed namespace for stable ids

# Menu sheet category label -> (enum, type)
CATS = {
    "Cigarettes": ("CIGARETTES", "RESALE"),
    "Tea & Coffee": ("TEA_COFFEE", "MADE"),
    "Milk & Shakes": ("MILK_SHAKES", "MADE"),
    "Juices & Sarbat": ("JUICES", "MADE"),
    "Cold Drinks": ("COLD_DRINKS", "RESALE"),
    "Snacks & Sweets": ("SNACKS", "RESALE"),
    "Kulhad Specials": ("KULHAD", "MADE"),
}

SIZE = {"🟢 Rs 30 Less": "LESS", "🟠 Regular": "REGULAR", "1 Serving": "SERVING"}

PREMIX = uuid.uuid5(NS, "raw:premix")
MILK = uuid.uuid5(NS, "raw:milk")
KULHAD_CUP = uuid.uuid5(NS, "raw:kulhad-cup")


def menu_id(num):
    return uuid.uuid5(NS, f"menu:{num}")


def inv_id(name):
    return uuid.uuid5(NS, f"inv:{name}")


def norm(s):
    return s.lower().replace("tea", "").replace(" ", "").strip()


def load():
    wb = openpyxl.load_workbook("MENU_AROGYA_Organized.xlsx", data_only=True)

    # Menu sheet -> rows of (num, name, category-label)
    menu = []
    for r in wb["Menu"].iter_rows(values_only=True):
        if r and isinstance(r[0], int):
            menu.append((r[0], r[1].strip(), r[2].strip()))

    # Ingredients sheet -> {normalized item name: [(order_size, milk_ml_or_None)]}
    ing = {}
    cur = None
    for r in wb["Ingredients"].iter_rows(values_only=True):
        if not r or len(r) < 5:
            continue
        num, name, size, sachet, milk = r[0], r[1], r[2], r[3], r[4]
        if isinstance(num, int) and name:
            cur = norm(str(name))
            ing.setdefault(cur, [])
        if size and str(size) in SIZE and cur:
            ml = None
            if milk and "ml" in str(milk):
                ml = int(str(milk).split("ml")[0].strip())
            ing[cur].append((SIZE[str(size)], ml))
    return menu, ing


def main():
    menu, ing = load()
    out = []
    out.append("-- Generated by scripts/gen_seed.py from MENU_AROGYA_Organized.xlsx")
    out.append("-- Quantities/thresholds default to 0; owner sets real levels + suppliers after.\n")

    # Raw materials
    out.append("insert into inventory_item (id, name, unit, quantity_on_hand, reorder_threshold) values")
    out.append(f"  ('{PREMIX}', 'Premix Sachet', 'SACHET', 0, 0),")
    out.append(f"  ('{MILK}', 'Milk', 'ML', 0, 0),")
    out.append(f"  ('{KULHAD_CUP}', 'Kulhad (clay cup)', 'PIECE', 0, 0);\n")

    resale = [(n, nm) for (n, nm, c) in menu if CATS[c][1] == "RESALE"]
    out.append("insert into inventory_item (id, name, unit, quantity_on_hand, reorder_threshold) values")
    rows = [f"  ('{inv_id(nm)}', {sql(nm)}, 'PIECE', 0, 0)" for _, nm in resale]
    out.append(",\n".join(rows) + ";\n")

    # Menu items
    out.append("insert into menu_item (id, name, category, type, resale_item_id) values")
    mrows = []
    for num, nm, clabel in menu:
        cat, typ = CATS[clabel]
        rid = f"'{inv_id(nm)}'" if typ == "RESALE" else "null"
        mrows.append(f"  ('{menu_id(num)}', {sql(nm)}, '{cat}', '{typ}', {rid})")
    out.append(",\n".join(mrows) + ";\n")

    # Recipe lines for MADE items
    out.append("insert into recipe_line (id, menu_item_id, order_size, inventory_item_id, quantity) values")
    lines = []
    for num, nm, clabel in menu:
        cat, typ = CATS[clabel]
        if typ != "MADE":
            continue
        sizes = ing.get(norm(nm)) or [("SERVING", None)]  # fallback: premix-only serving
        is_kulhad = "kulhad" in nm.lower()
        for size, ml in sizes:
            lid = lambda tag: uuid.uuid5(NS, f"rl:{num}:{size}:{tag}")
            lines.append(f"  ('{lid('premix')}', '{menu_id(num)}', '{size}', '{PREMIX}', 1)")
            if ml:
                lines.append(f"  ('{lid('milk')}', '{menu_id(num)}', '{size}', '{MILK}', {ml})")
            if is_kulhad:
                lines.append(f"  ('{lid('cup')}', '{menu_id(num)}', '{size}', '{KULHAD_CUP}', 1)")
    out.append(",\n".join(lines) + ";\n")

    with open("src/main/resources/db/migration/V2__seed.sql", "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"Wrote V2__seed.sql: {len(resale)} resale + 3 raw items, {len(menu)} menu, {len(lines)} recipe lines")


def sql(s):
    return "'" + s.replace("'", "''") + "'"


if __name__ == "__main__":
    main()
