apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cafe-test-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shankhanraman/cafe_test.git
    targetRevision: HEAD
    path: infra/k8s/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: cafe-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
