apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cafe-test
spec:
  selector:
    app: cafe-test-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None # headless — stable DNS: postgres.cafe-test.svc.cluster.local
